# Builds i18n/site.js from i18n/site.tsv (EN|DE|ES|PL|FR|PT|IT). Run after editing the TSV.
import json,os
here=os.path.dirname(os.path.abspath(__file__))
rows=[l.rstrip('\n').split('|') for l in open(os.path.join(here,'site.tsv'),encoding='utf-8') if l.strip()]
head,rows=rows[0],rows[1:]
bad=[r for r in rows if len(r)!=7]
assert not bad, bad[:2]
D={r[0]:r[1:] for r in rows}
eng=open(os.path.join(here,'engine.js'),encoding='utf-8').read()
open(os.path.join(here,'site.js'),'w',encoding='utf-8').write('/* generated by i18n/build.py — edit site.tsv */\n'+eng.replace('__DICT__',json.dumps(D,ensure_ascii=False)))
print(len(D),'strings')
